name: book_share
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: ^2.4.1
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.1
  image_picker: ^0.6.7+12
  firebase_storage: ^4.0.1
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  multiselect_formfield: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
      - family: Billabong
        fonts:
          - asset: assets/fonts/Billabong.ttf
  assets:
  - assets/images/


